version: "3.7"
services:
  client:
    build: ./client
    restart: always
    ports:
      - "3030:3000"
    volumes:
      - ./client:/client
    links:
      - api
    environment:
      - CI=true

  api:
    build: ./api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
      - /api/node_modules


